# Generated by Django 5.2.3 on 2025-06-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdetails',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='taskdetails',
            name='notess',
        ),
        migrations.AddField(
            model_name='taskdetails',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
